language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -e .
  - pip install mypy flake8
# command to check that it was installed correctly
script:
  - kindroam
  - mypy --ignore-missing-imports src/
  - flake8 src/
